 SET FOREIGN_KEY_CHECKS=0;
 INSERT INTO `kategorie` VALUES 
 (1,'kniha','Knihy'),
 (2,'kontakt','Kontakty'),
 (3,'publikácia','Publikácie'),
 (4,'projekt','Projekty'),
 (5,'posudok','Posudky'),
 (6,'konferencia','Konferencie'),
 (7,'podujatie','Podujatia'),
 (8,'pracovná cesta','Pracovné cesty'),
 (9,'evidencia majektu','Evidencia majetku'),
 (10,'softvér','Softvér'),
 (11,'záverečná práca','Záverečné práce'),
 (12,'spolupráca','Spolupráca'),
 (13,'web','Weby');
 
 INSERT INTO `atributy` VALUES (1,'Názov','text',1),
 (2,'Autor','text',1),
 (3,'Vydavateľstvo','text',1),
 (4,'zaner','text',1),
 (5,'Meno','text',2),
 (6,'Priezvisko','text',2),
 (7,'Adresa','text',2),
 (8,'E-mail','text',2),
 (9,'Telefón','text',2),
 (10,'Pôsobisko','text',2),
 (11,'Pracovná pozícia','text',2),
 (12,'Vznik kontaktu','text',2),
 (13,'Názov','text',3),
 (14,'Autori','text',3),
 (15,'Typ','select',3),
 (16,'Rok vydania','number',3),
 (17,'Volume','text',3),(18,'Číslo','text',3),
 (19,'Strany','text',3),(20,'Vydavateľstvo','text',3),
 (21,'Vyšlo v','text',3),
 (22,'Doi','text',3),
 (23,'Názov','text',4),
 (24,'Hlavný riešiteľ','text',4),
 (25,'Popis','textarea',4),
 (26,'Ostatní riešitelia','text',4),
 (27,'Trvanie','dateinterval',4),
 (28,'Stav projektu','select',4),
 (29,'Typ','text',4),
 (30,'Názov posudzovaného diela','text',5),
 (31,'Autori posudzovaného diela','text',5),
 (32,'Typ diela','select',5),
 (33,'Udalosť','text',5),
 (34,'Názov','text',6),
 (35,'Skratka','text',6),
 (36,'Dátum začiatku','dateinterval',6),
 (37,'Miesto','text',6),
 (38,'Organizátor','text',6),
 (39,'Dátum poslania abstraktu','date',6),
 (40,'Dátum akceptácie','date',6),
 (41,'Camera ready deadline','date',6),
 (42,'Early registration deadline','date',6),
 (43,'Normal registration deadline','date',6),
 (44,'Paper submission deadline','date',6),
 (45,'Názov','text',7),
 (46,'Skratka','text',7),
 (47,'Popis','textarea',7),
 (48,'Dátum začiatku','dateinterval',7),
 (49,'Adresa podujatia','text',7),
 (50,'Typ','select',7),
 (51,'Zdroj financovania','text',7),
 (52,'Počet ľudí','number',7),
 (53,'Nahlásené','checkbox',7),
 (54,'Meno kontaktnej osoby','text',7),
 (55,'E-mail','text',7),
 (56,'Telefón','text',7),
 (57,'Udalosť','text',8),
 (58,'Miesto','text',8),
 (59,'Dátum začiatku','dateinterval',8),
 (60,'Zdroj financovania','text',8),
 (61,'Účastníci','text',8),
 (62,'Názov','text',9),
 (63,'Cena','number',9),
 (64,'Mena','text',9),
 (65,'Cena v eurách','number',9),
 (66,'Dátum nadobudnutia','date',9),
 (67,'Účel nadobudnutia','text',9),
 (68,'Zdroj financovania','text',9),
 (69,'Miestnosť','text',9),(70,'Miesto v miestnosti','text',9),
 (71,'Názov produktu','text',10),(72,'Cena','number',10),
 (73,'Verzia','text',10),(74,'Výrobca','text',10),
 (75,'Licencia produktu','text',10),
 (76,'Popis','textarea',10),
 (77,'Názov','text',11),
 (78,'Študent','text',11),
 (79,'Typ','select',11),
 (80,'Predpokladaný rok ukončenia','number',11),
 (81,'Cieľ','text',11),
 (82,'Moja rola','select',11),
 (83,'Názov spoločnosti','text',12),
 (84,'Kontaktná osoba','text',12),
 (85,'Telefón','text',12),
 (86,'E-mail','text',12),
 (87,'Adresa sídla','textarea',12),
 (88,'Bankový kontakt','text',12),
 (89,'Ičo','text',12),(90,'Zmluva','checkbox',12),
 (91,'Dátum expirácie zmluvy','date',12),
 (92,'Názov','text',13),
 (93,'Url','text',13),
 (94,'Meno servera','text',13),
 (95,'Kontakt na používateľa','text',13),
 (96,'Kontakt na autora','text',13),
 (97,'Účel','text',13),
 (98,'Softvérové požiadavky','textarea',13),
 (99,'Automatický backup','checkbox',13);
 
  SET FOREIGN_KEY_CHECKS=1;

 